version: '3'
services:
  todoback:
    image: todobackend
    ports: 
      - 3001:3001
    restart: always
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - todoback
    environment: 
      - REACT_APP_API_HOST=todoback
  todotests:
    depends_on:
      - todoback
      - todofront
    image: todotests
    restart: always
    environment:
      - FRONT_HOST=todofront
  